export enum ServiceStatus {
    SUCCESS = "SUCCESS",
    FAILURE = "FAILURE",
    UNAUTHORIZED = "UNAUTHORIZED",
    NOT_FOUND = "NOT_FOUND",
    VALIDATION_ERROR = "VALIDATION_ERROR",
    CONFLICT = "CONFLICT",
    INTERNAL_ERROR = "INTERNAL_ERROR"
}
